# \u670D\u52A1\u7AEF\u53E3\u53F78081
#server.port=8081
#spring.datasource.url=jdbc:mysql://localhost:3306/uniapp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/uniapp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
# \u9ED8\u8BA4\u503C\u4E3Atrue
#mybatis-plus.configuration.map-underscore-to-camel-case=true
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
#
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#server.servlet.encoding.force=true
#server.servlet.encoding.charset=UTF-8
Bath:
  Path: D:/image1/
  Code1: sh000985
  Code2: sh000300
  Code3: sh000001
  secret: osJKzjyy6v4NNALRIHfUAg==